[package]
name = "monokakido"
version = "0.3.1"
edition = "2021"
description = "A Rust library for parsing and interpreting the Monokakido dictionary format."
license = "MIT"

[dependencies]
miniz_oxide = { version = "0.7", default-features = false }
miniserde = "0.1"
xmlparser = "0.13.5"
